version: 2.1

orbs:
  win: circleci/windows@2.4.0
  jira: circleci/jira@1.3.1

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: choco install cmake -y
      - run:
         name: Setting CMake environmental variable
         command: set PATH="C:\Program Files\CMake\bin\";%PATH%
      - run: 
         name: Checking CMake version
         command: cmake --version
   

workflows:
  version: 2
  run-all:
    jobs:
      - build
   
          