version: 2.1

orbs:
  win: circleci/windows@2.4.0
  jira: circleci/jira@1.3.1

jobs:
  prepare_env:
    executor: win/default
    steps:
      - checkout
      - run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' 
      - run: choco install mingw
      - run: gcc --version
      - run: gcov --version
      - run: cmake --version
      - run: cmake -G "MinGW Make" -S src -B "build/src" -C "build/src" 

          
  checks:
    executor: win/default
    steps:
      - run: cmake --version
      - run: gcc --version
      - run: gcov --version
      
      
          
  build:
    executor: win/default
    steps:
       - checkout
       - run: 
          command: echo Build
   
  test:
    executor: win/default
    steps:
      - checkout
      - run: 
         command: echo Test
   
  coverage:
    executor: win/default
    steps:
      - run: 
          command: echo Coverage
          
      
      
workflows:
  version: 2
  run-all:
    jobs:
      - prepare_env
      - checks:
          requires:
            - prepare_env
      - build:
          requires:
            - checks
      - test:
          requires:
            - build
      - coverage:
          requires:
            - test
      
         