version: 2.1

orbs:
  win: circleci/windows@2.4.0
  jira: circleci/jira@1.3.1
  cmake: sensu/cmake@1.0.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: ls
      - cmake/install:
        install-dir: .\CMake
      

workflows:
  version: 2
  run-all:
    jobs:
      - build
         