version: 2.1

orbs:
  win: circleci/windows@2.4.0
  jira: circleci/jira@1.0.5

jobs:
  run_tests:
    executor: win/default
    steps:
      - checkout
      - run: New-Item -Path "C:\Users\circleci\project" -Name "build" -ItemType "directory"
      - run: cmake -S src -B "/build"
      - run: cd ./build/
      - run: Get-ChildItem -Directory
      - run: make
          
      
      
workflows:
  version: 2
  run-all:
    jobs:
      - run_tests
      
         