version: 2.1

orbs:
  win: circleci/windows@2.4.0
  jira: circleci/jira@1.3.1
  cmake: sensu/cmake@1.0.0

jobs:
  checks:
    executor: win/default
    steps:
      - run: gcc --version
      - run: gcov --version
      - run: cmake --version
      
      
workflows:
  version: 2
  run-all:
    jobs:
      - checks
         