version: 2.1

orbs:
  win: circleci/windows@2.4.0
  jira: circleci/jira@1.3.1

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: choco install cmake -y
      - run: $env:Path+=";$Env:ProgramFiles\CMake\bin"
      - run: cmake --version
   

workflows:
  version: 2
  run-all:
    jobs:
      - build
   
          