version: 2.1

orbs:
  win: circleci/windows@2.4.0
  jira: circleci/jira@1.3.1

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - name: Installing CMake
      - run: choco install cmake -y
      - name: Setting CMake Environmental Variable
      - command: echo 'export PATH=C:\Program Files\CMake\bin:$PATH' >> $BASH_ENV
      - name: Testing CMake
      - run: cmake --version
   

workflows:
  version: 2
  run-all:
    jobs:
      - build
   
          