version: 2.1

orbs:
  win: circleci/windows@2.4.0
  jira: circleci/jira@1.3.1
  cmake: sensu/cmake@1.0.0

jobs:
  cmake_install:
    executor: win/default
    steps:
      - cmake/install

  
  build:
    executor: win/default
    steps:
      - checkout
      - run: cmake/install
   

workflows:
  version: 2
  run-all:
    jobs:
      - cmake_install
      - build
   
          