version: 2.1

orbs:
  win: circleci/windows@2.4.0
  jira: circleci/jira@1.3.1

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: ls
      - run: choco install cmake
      - run:
         command: echo 'export PATH="'C:/Program Files/CMake/bin:$PATH"' >> $BASH_ENV
      

workflows:
  version: 2
  run-all:
    jobs:
      - build
         