version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: gcc --version
   

workflows:
  version: 2
  run-all:
    jobs:
      - build
   
          