version: 2.1

orbs:
  win: circleci/windows@2.4.0
  jira: circleci/jira@1.0.5

jobs:
  run_tests:
    executor: win/default
    steps:
      - checkout
      - run: choco install mingw
      - run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      - run: cd ./build/
      - run: cmake --build .
      - run: make
          
      
      
workflows:
  version: 2
  run-all:
    jobs:
      - run_tests
      
         