version: 2.1

orbs:
  win: circleci/windows@2.4.0
  jira: circleci/jira@1.3.1

jobs:
  prepare_env:
    executor: win/default
    steps:
      - run: choco install cmake      
      - run: choco install mingw
          
  checks:
    executor: win/default
    steps:
      - run: 
          command: cmake --version
      - run: 
          command: gcc --version
      - run:
          command: gcov --version
          
  build:
    executor: win/default
    steps:
       - run: 
          command: echo Build
   
  test:
    executor: win/default
    steps:
      - run: 
         command: echo Test
   
  coverage:
    executor: win/default
    steps:
      - run: 
          command: echo Coverage
          
      
      
workflows:
  version: 2
  run-all:
    jobs:
      - prepare_env
      - checks:
          requires:
            - prepare_env
      - build:
          requires:
            - checks
      - test:
          requires:
            - build
      - coverage:
          requires:
            - test
         